/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  supplyChainSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Supply Chain',
      link: {type: 'doc', id: 'supply-chain/overview'},
      items: [
        {
          type: 'category',
          label: 'Procurement',
          items: [{type: 'autogenerated', dirName: 'supply-chain/procurement'}],
        },
        {
          type: 'category',
          label: 'Warehouse & DC Operations',
          items: [{type: 'autogenerated', dirName: 'supply-chain/warehouse'}],
        },
        {
          type: 'category',
          label: 'Transportation',
          items: [{type: 'autogenerated', dirName: 'supply-chain/transportation'}],
        },
        {
          type: 'category',
          label: 'Inventory Management',
          items: [{type: 'autogenerated', dirName: 'supply-chain/inventory'}],
        },
        {
          type: 'category',
          label: 'Returns & Reverse Logistics',
          items: [{type: 'autogenerated', dirName: 'supply-chain/returns'}],
        },
      ],
    },
  ],

  systemsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Systems',
      link: {type: 'doc', id: 'systems/overview'},
      items: [
        {
          type: 'category',
          label: 'WMS (Warehouse Management)',
          items: [{type: 'autogenerated', dirName: 'systems/wms'}],
        },
        {
          type: 'category',
          label: 'TMS (Transportation Management)',
          items: [{type: 'autogenerated', dirName: 'systems/tms'}],
        },
        {
          type: 'category',
          label: 'Inventory Systems',
          items: [{type: 'autogenerated', dirName: 'systems/inventory-systems'}],
        },
        {
          type: 'category',
          label: 'Integrations & EDI',
          link: {type: 'doc', id: 'systems/integrations/overview'},
          items: [
            {type: 'autogenerated', dirName: 'systems/integrations/edi'},
            'systems/integrations/apis',
            'systems/integrations/data-flows',
          ],
        },
      ],
    },
  ],

  referenceSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Reference',
      items: [{type: 'autogenerated', dirName: 'reference'}],
    },
  ],
};

export default sidebars;
